
USE brandix_bts;

CREATE TABLE delete_log( `sno` INT(10) NOT NULL AUTO_INCREMENT, `date_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP, `user` VARCHAR(255) NOT NULL, `style` VARCHAR(255), `schedule` VARCHAR(255), `color` VARCHAR(255), PRIMARY KEY (`sno`) ) ENGINE=INNODB CHARSET=latin1 COLLATE=latin1_swedish_ci; 


