		
<link rel="stylesheet" href="sfcs_app/app/dashboards/common/css/styles.css">
<div class="container">
		<div class="panel panel-primary">
			 <div class="panel-heading"> Factory View for Production KPI <a href='sfcs_app/app/dashboards/controllers/Factory_View/factory_view.htm' target="_blank" class='btn btn-success pull-right'>?</a></div>
				<div class="panel-body">
					<div class="table-responsive">
                      <table align="center" class="table table-bordered">
                      <thead><tr><th>Performance / Section</th><th><a href='http://localhost//index.php?r=L3NmY3NfYXBwL2FwcC9kYXNoYm9hcmRzL2NvbnRyb2xsZXJzL0ZhY3RvcnlfVmlldy9mYWN0b3J5X3ZpZXcucGhw&sec_x=1' target='_blank'>1</a></th><th><a href='http://localhost//index.php?r=L3NmY3NfYXBwL2FwcC9kYXNoYm9hcmRzL2NvbnRyb2xsZXJzL0ZhY3RvcnlfVmlldy9mYWN0b3J5X3ZpZXcucGhw&sec_x=2' target='_blank'>2</a></th><th><a href='http://localhost//index.php?r=L3NmY3NfYXBwL2FwcC9kYXNoYm9hcmRzL2NvbnRyb2xsZXJzL0ZhY3RvcnlfVmlldy9mYWN0b3J5X3ZpZXcucGhw&sec_x=3' target='_blank'>3</a></th><th><a href='http://localhost//index.php?r=L3NmY3NfYXBwL2FwcC9kYXNoYm9hcmRzL2NvbnRyb2xsZXJzL0ZhY3RvcnlfVmlldy9mYWN0b3J5X3ZpZXcucGhw&sec_x=4' target='_blank'>4</a></th><th><a href='http://localhost//index.php?r=L3NmY3NfYXBwL2FwcC9kYXNoYm9hcmRzL2NvbnRyb2xsZXJzL0ZhY3RvcnlfVmlldy9mYWN0b3J5X3ZpZXcucGhw&sec_x=6' target='_blank'>6</a></th><th><a href='http://localhost//index.php?r=L3NmY3NfYXBwL2FwcC9kYXNoYm9hcmRzL2NvbnRyb2xsZXJzL0ZhY3RvcnlfVmlldy9mYWN0b3J5X3ZpZXcucGhw&sec_x=8' target='_blank'>8</a></th><th><a href='http://localhost//index.php?r=L3NmY3NfYXBwL2FwcC9kYXNoYm9hcmRzL2NvbnRyb2xsZXJzL0ZhY3RvcnlfVmlldy9mYWN0b3J5X3ZpZXcucGhw&sec_x=9' target='_blank'>9</a></th><th><a href='http://localhost//index.php?r=L3NmY3NfYXBwL2FwcC9kYXNoYm9hcmRzL2NvbnRyb2xsZXJzL0ZhY3RvcnlfVmlldy9mYWN0b3J5X3ZpZXcucGhw&sec_x=10' target='_blank'>10</a></th></tr> </thead>							
					<tbody>
							<tr><td class="heading">Plan/RM (IPS)</td><td><div id="yellow"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/fab_pps_dashboard_v2_live.php?sec_x=1&rand=218217229" target='_blank'></a></div></td><td><div id="yellow"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/fab_pps_dashboard_v2_live.php?sec_x=2&rand=248973169" target='_blank'></a></div></td><td><div id="yellow"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/fab_pps_dashboard_v2_live.php?sec_x=3&rand=1919193170" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/fab_pps_dashboard_v2_live.php?sec_x=4&rand=1326088953" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/fab_pps_dashboard_v2_live.php?sec_x=6&rand=1855957522" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/fab_pps_dashboard_v2_live.php?sec_x=8&rand=1791576022" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/fab_pps_dashboard_v2_live.php?sec_x=9&rand=37199853" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/fab_pps_dashboard_v2_live.php?sec_x=10&rand=258127232" target='_blank'></a></div></td>
</tr>



							<tr><td class="heading">Work In Progress (IMS)</td>

<td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/cpanel_main_live_dashboard.php?sec_x=1&rand=1814690772" target='_blank'></a></div></td><td><div id="red"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/cpanel_main_live_dashboard.php?sec_x=2&rand=340856284" target='_blank'></a></div></td><td><div id="red"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/cpanel_main_live_dashboard.php?sec_x=3&rand=944096027" target='_blank'></a></div></td><td><div id="yellow"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/cpanel_main_live_dashboard.php?sec_x=4&rand=819061150" target='_blank'></a></div></td><td><div id="red"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/cpanel_main_live_dashboard.php?sec_x=6&rand=869017110" target='_blank'></a></div></td><td><div id="yellow"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/cpanel_main_live_dashboard.php?sec_x=8&rand=478580322" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/cpanel_main_live_dashboard.php?sec_x=9&rand=1404035434" target='_blank'></a></div></td><td><div id="red"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/cpanel_main_live_dashboard.php?sec_x=10&rand=1099753547" target='_blank'></a></div></td></tr>


							<tr><td class="heading" >Rework (RLS) </td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/section_rls_live.php?sec_x=1&rand=1939141037" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/section_rls_live.php?sec_x=2&rand=1524243727" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/section_rls_live.php?sec_x=3&rand=1926732005" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/section_rls_live.php?sec_x=4&rand=1836154018" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/section_rls_live.php?sec_x=6&rand=1769223581" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/section_rls_live.php?sec_x=8&rand=2042603667" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/section_rls_live.php?sec_x=9&rand=1341577357" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/section_rls_live.php?sec_x=10&rand=369891865" target='_blank'></a></div></td></tr>

							<tr><td class="heading" >FG Controlling (LMS) </td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/packing_dashboard_live_dashboard.php?sec_x=1&rand=1296082527" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/packing_dashboard_live_dashboard.php?sec_x=2&rand=1189887476" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/packing_dashboard_live_dashboard.php?sec_x=3&rand=820691186" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/packing_dashboard_live_dashboard.php?sec_x=4&rand=415097749" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/packing_dashboard_live_dashboard.php?sec_x=6&rand=916530607" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/packing_dashboard_live_dashboard.php?sec_x=8&rand=1981221528" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/packing_dashboard_live_dashboard.php?sec_x=9&rand=1885458291" target='_blank'></a></div></td><td><div id="green"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/packing_dashboard_live_dashboard.php?sec_x=10&rand=955267534" target='_blank'></a></div></td></tr>



							<tr><td class="heading" >SAH Generation (LIVE) </td><!--
Changes Log:

1)2013-11-30/kirang/Ticket#668916
Factory KPI Dashboard Changes
"1) Individual section Plan SAH must come based on the Hours.
2) Factory KPI dashboard SAH should be equal to today only.
* Need to change Act SAH, CLH based on hours."

SAH live  - achievement  90% to 99%  yellow 
                     SAH achievement 100% and above Green
                    SAH achievement less than 90% is Red.
					
2)2014-03-27/kirang/Ticket #439900/ To avoid the division by Zero error at SAH Generation in Factory view 

-->
<td><div id="red"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/sah_live_dashboard_V2.php?sec_x=1&rand=1845548519" target='_blank'></a></div></td><td><div id="red"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/sah_live_dashboard_V2.php?sec_x=2&rand=1503602167" target='_blank'></a></div></td><td><div id="red"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/sah_live_dashboard_V2.php?sec_x=3&rand=52131820" target='_blank'></a></div></td><td><div id="red"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/sah_live_dashboard_V2.php?sec_x=4&rand=935774070" target='_blank'></a></div></td><td><div id="red"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/sah_live_dashboard_V2.php?sec_x=6&rand=280670137" target='_blank'></a></div></td><td><div id="red"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/sah_live_dashboard_V2.php?sec_x=8&rand=432627540" target='_blank'></a></div></td><td><div id="red"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/sah_live_dashboard_V2.php?sec_x=9&rand=1745521935" target='_blank'></a></div></td><td><div id="red"><a href="http://localhost/sfcs_app/app/dashboards/controllers/Factory_View/sah_live_dashboard_V2.php?sec_x=10&rand=87141561" target='_blank'></a></div></td></tr>


							<!-- <tr><td class="heading" >Absenteeism (LIVE HR) </td><td><div id="red"><a href="/projects/Beta/Reports/Production_Live_Chart/Control_Room_Charts/Dash_Board_new.php?sec_x=1&rand=1749643944" target='_blank'></a></div></td><td><div id="red"><a href="/projects/Beta/Reports/Production_Live_Chart/Control_Room_Charts/Dash_Board_new.php?sec_x=2&rand=1161088684" target='_blank'></a></div></td><td><div id="red"><a href="/projects/Beta/Reports/Production_Live_Chart/Control_Room_Charts/Dash_Board_new.php?sec_x=3&rand=1415796736" target='_blank'></a></div></td><td><div id="red"><a href="/projects/Beta/Reports/Production_Live_Chart/Control_Room_Charts/Dash_Board_new.php?sec_x=4&rand=322625724" target='_blank'></a></div></td><td><div id="red"><a href="/projects/Beta/Reports/Production_Live_Chart/Control_Room_Charts/Dash_Board_new.php?sec_x=6&rand=1485335030" target='_blank'></a></div></td><td><div id="red"><a href="/projects/Beta/Reports/Production_Live_Chart/Control_Room_Charts/Dash_Board_new.php?sec_x=8&rand=614395236" target='_blank'></a></div></td><td><div id="red"><a href="/projects/Beta/Reports/Production_Live_Chart/Control_Room_Charts/Dash_Board_new.php?sec_x=9&rand=917943006" target='_blank'></a></div></td><td><div id="red"><a href="/projects/Beta/Reports/Production_Live_Chart/Control_Room_Charts/Dash_Board_new.php?sec_x=10&rand=188132458" target='_blank'></a></div></td></tr> -->
					</tbody>
					
					</table>
				</div>
			</div>
		</div>
</div>

