/*
SQLyog Community
MySQL - 10.3.8-MariaDB : Database - bai_pro4
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`bai_pro4` /*!40100 DEFAULT CHARACTER SET latin1 */;

/*USE `bai_pro4`;*/

/*Table structure for table `fastreact_plan` */

DROP TABLE IF EXISTS `bai_pro4`.`fastreact_plan`;

CREATE TABLE `bai_pro4`.`fastreact_plan` (
  `group_code` varchar(20) NOT NULL COMMENT 'Style Name',
  `module` varchar(8) NOT NULL COMMENT 'Module No\r\n',
  `style` varchar(130) NOT NULL COMMENT 'Style Id\r\n',
  `order_code` varchar(300) NOT NULL COMMENT 'Order Tid \r\n',
  `color` varchar(200) NOT NULL COMMENT 'Color Name\r\n',
  `smv` double NOT NULL COMMENT 'SMV\r\n',
  `delivery_date` date NOT NULL COMMENT 'Exfactory Date\r\n',
  `schedule` varchar(300) NOT NULL COMMENT 'Schedule No\r\n',
  `production_date` date NOT NULL COMMENT 'Production Statr Date\r\n',
  `qty` double NOT NULL COMMENT 'Order Qty\r\n',
  `tid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'Trace id\r\n',
  `week_code` int(11) NOT NULL COMMENT 'Week No\r\n',
  `status` int(11) NOT NULL COMMENT 'Status\r\n',
  PRIMARY KEY (`tid`),
  KEY `style` (`schedule`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Table structure for table `job_shipment_plan_man_up` */

DROP TABLE IF EXISTS `bai_pro4`.`job_shipment_plan_man_up`;

CREATE TABLE `bai_pro4`.`job_shipment_plan_man_up` (
  `DELIVERY_NO` varchar(30) NOT NULL,
  `SCHEDULE_NO` varchar(30) NOT NULL,
  `ORD_QTY` varchar(30) NOT NULL,
  `FOB_PRICE_PER_PIECE` varchar(30) NOT NULL,
  `CM_VALUE` varchar(30) NOT NULL,
  `EX_FACTORY_DATE` varchar(30) NOT NULL,
  `ORDER_NO` varchar(10) NOT NULL,
  `STYLE` varchar(15) NOT NULL,
  `SIZE` varchar(15) NOT NULL,
  `Z_FEATURE` varchar(15) NOT NULL,
  `DEL_STATUS` varchar(2) NOT NULL,
  `MODE` varchar(3) NOT NULL,
  `PACKING_METHOD` varchar(3) NOT NULL,
  `MPO` varchar(30) NOT NULL,
  `CPO` varchar(30) NOT NULL,
  `COLOR` varchar(30) NOT NULL,
  `BUYER` varchar(36) NOT NULL,
  `PRODUCT` varchar(40) NOT NULL,
  `BUYER_DIVISION` varchar(40) NOT NULL,
  `DESTINATION` varchar(6) NOT NULL,
  `A` varchar(3) NOT NULL DEFAULT '0',
  `B` varchar(3) NOT NULL DEFAULT '0',
  `C` varchar(3) NOT NULL DEFAULT '0',
  `D` varchar(3) NOT NULL DEFAULT '0',
  `E` varchar(3) NOT NULL DEFAULT '0',
  `F` varchar(3) NOT NULL DEFAULT '0',
  `G` varchar(3) NOT NULL DEFAULT '0',
  `H` varchar(3) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `members` */

DROP TABLE IF EXISTS `bai_pro4`.`members`;

CREATE TABLE `bai_pro4`.`members` (
  `member_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `firstname` varchar(100) DEFAULT NULL,
  `lastname` varchar(100) DEFAULT NULL,
  `login` varchar(100) NOT NULL DEFAULT '',
  `passwd` varchar(32) NOT NULL DEFAULT '',
  `level` int(11) NOT NULL,
  PRIMARY KEY (`member_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Table structure for table `query_edit_log` */

DROP TABLE IF EXISTS `bai_pro4`.`query_edit_log`;

CREATE TABLE `bai_pro4`.`query_edit_log` (
  `log_id` int(6) NOT NULL AUTO_INCREMENT,
  `log_time` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `query_executed` text NOT NULL,
  `user_name` varchar(11) DEFAULT NULL,
  PRIMARY KEY (`log_id`),
  KEY `NewIndex1` (`log_id`,`log_time`),
  KEY `NewIndex2` (`log_time`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `shipfast_sum` */

DROP TABLE IF EXISTS `bai_pro4`.`shipfast_sum`;

CREATE TABLE `bai_pro4`.`shipfast_sum` (
  `shipment_plan_id` int(11) NOT NULL,
  `fastreact_plan_id` int(11) NOT NULL,
  `size_xs` int(11) NOT NULL,
  `size_s` int(11) NOT NULL,
  `size_m` int(11) NOT NULL,
  `size_l` int(11) NOT NULL,
  `size_xl` int(11) NOT NULL,
  `size_xxl` int(11) NOT NULL,
  `size_xxxl` int(11) NOT NULL,
  `size_s01` int(11) NOT NULL,
  `size_s02` int(11) NOT NULL,
  `size_s03` int(11) NOT NULL,
  `size_s04` int(11) NOT NULL,
  `size_s05` int(11) NOT NULL,
  `size_s06` int(11) NOT NULL,
  `size_s07` int(11) NOT NULL,
  `size_s08` int(11) NOT NULL,
  `size_s09` int(11) NOT NULL,
  `size_s10` int(11) NOT NULL,
  `size_s11` int(11) NOT NULL,
  `size_s12` int(11) NOT NULL,
  `size_s13` int(11) NOT NULL,
  `size_s14` int(11) NOT NULL,
  `size_s15` int(11) NOT NULL,
  `size_s16` int(11) NOT NULL,
  `size_s17` int(11) NOT NULL,
  `size_s18` int(11) NOT NULL,
  `size_s19` int(11) NOT NULL,
  `size_s20` int(11) NOT NULL,
  `size_s21` int(11) NOT NULL,
  `size_s22` int(11) NOT NULL,
  `size_s23` int(11) NOT NULL,
  `size_s24` int(11) NOT NULL,
  `size_s25` int(11) NOT NULL,
  `size_s26` int(11) NOT NULL,
  `size_s27` int(11) NOT NULL,
  `size_s28` int(11) NOT NULL,
  `size_s29` int(11) NOT NULL,
  `size_s30` int(11) NOT NULL,
  `size_s31` int(11) NOT NULL,
  `size_s32` int(11) NOT NULL,
  `size_s33` int(11) NOT NULL,
  `size_s34` int(11) NOT NULL,
  `size_s35` int(11) NOT NULL,
  `size_s36` int(11) NOT NULL,
  `size_s37` int(11) NOT NULL,
  `size_s38` int(11) NOT NULL,
  `size_s39` int(11) NOT NULL,
  `size_s40` int(11) NOT NULL,
  `size_s41` int(11) NOT NULL,
  `size_s42` int(11) NOT NULL,
  `size_s43` int(11) NOT NULL,
  `size_s44` int(11) NOT NULL,
  `size_s45` int(11) NOT NULL,
  `size_s46` int(11) NOT NULL,
  `size_s47` int(11) NOT NULL,
  `size_s48` int(11) NOT NULL,
  `size_s49` int(11) NOT NULL,
  `size_s50` int(11) NOT NULL,
  `plan_start_date` date NOT NULL,
  `plan_comp_date` date NOT NULL,
  `size_comp_xs` int(11) NOT NULL,
  `size_comp_s` int(11) NOT NULL,
  `size_comp_m` int(11) NOT NULL,
  `size_comp_l` int(11) NOT NULL,
  `size_comp_xl` int(11) NOT NULL,
  `size_comp_xxl` int(11) NOT NULL,
  `size_comp_xxxl` int(11) NOT NULL,
  `size_comp_s01` int(11) NOT NULL COMMENT 'Shipment Size s01',
  `size_comp_s02` int(11) NOT NULL COMMENT 'Shipment Size s02',
  `size_comp_s03` int(11) NOT NULL COMMENT 'Shipment Size s03',
  `size_comp_s04` int(11) NOT NULL COMMENT 'Shipment Size s04',
  `size_comp_s05` int(11) NOT NULL COMMENT 'Shipment Size s05',
  `size_comp_s06` int(11) NOT NULL COMMENT 'Shipment Size s06',
  `size_comp_s07` int(11) NOT NULL COMMENT 'Shipment Size s07',
  `size_comp_s08` int(11) NOT NULL COMMENT 'Shipment Size s08',
  `size_comp_s09` int(11) NOT NULL COMMENT 'Shipment Size s09',
  `size_comp_s10` int(11) NOT NULL COMMENT 'Shipment Size s10',
  `size_comp_s11` int(11) NOT NULL COMMENT 'Shipment Size s11',
  `size_comp_s12` int(11) NOT NULL COMMENT 'Shipment Size s12',
  `size_comp_s13` int(11) NOT NULL COMMENT 'Shipment Size s13',
  `size_comp_s14` int(11) NOT NULL COMMENT 'Shipment Size s14',
  `size_comp_s15` int(11) NOT NULL COMMENT 'Shipment Size s15',
  `size_comp_s16` int(11) NOT NULL COMMENT 'Shipment Size s16',
  `size_comp_s17` int(11) NOT NULL COMMENT 'Shipment Size s17',
  `size_comp_s18` int(11) NOT NULL COMMENT 'Shipment Size s18',
  `size_comp_s19` int(11) NOT NULL COMMENT 'Shipment Size s19',
  `size_comp_s20` int(11) NOT NULL COMMENT 'Shipment Size s20',
  `size_comp_s21` int(11) NOT NULL COMMENT 'Shipment Size s21',
  `size_comp_s22` int(11) NOT NULL COMMENT 'Shipment Size s22',
  `size_comp_s23` int(11) NOT NULL COMMENT 'Shipment Size s23',
  `size_comp_s24` int(11) NOT NULL COMMENT 'Shipment Size s24',
  `size_comp_s25` int(11) NOT NULL COMMENT 'Shipment Size s25',
  `size_comp_s26` int(11) NOT NULL COMMENT 'Shipment Size s26',
  `size_comp_s27` int(11) NOT NULL COMMENT 'Shipment Size s27',
  `size_comp_s28` int(11) NOT NULL COMMENT 'Shipment Size s28',
  `size_comp_s29` int(11) NOT NULL COMMENT 'Shipment Size s29',
  `size_comp_s30` int(11) NOT NULL COMMENT 'Shipment Size s30',
  `size_comp_s31` int(11) NOT NULL COMMENT 'Shipment Size s31',
  `size_comp_s32` int(11) NOT NULL COMMENT 'Shipment Size s32',
  `size_comp_s33` int(11) NOT NULL COMMENT 'Shipment Size s33',
  `size_comp_s34` int(11) NOT NULL COMMENT 'Shipment Size s34',
  `size_comp_s35` int(11) NOT NULL COMMENT 'Shipment Size s35',
  `size_comp_s36` int(11) NOT NULL COMMENT 'Shipment Size s36',
  `size_comp_s37` int(11) NOT NULL COMMENT 'Shipment Size s37',
  `size_comp_s38` int(11) NOT NULL COMMENT 'Shipment Size s38',
  `size_comp_s39` int(11) NOT NULL COMMENT 'Shipment Size s39',
  `size_comp_s40` int(11) NOT NULL COMMENT 'Shipment Size s40',
  `size_comp_s41` int(11) NOT NULL COMMENT 'Shipment Size s41',
  `size_comp_s42` int(11) NOT NULL COMMENT 'Shipment Size s42',
  `size_comp_s43` int(11) NOT NULL COMMENT 'Shipment Size s43',
  `size_comp_s44` int(11) NOT NULL COMMENT 'Shipment Size s44',
  `size_comp_s45` int(11) NOT NULL COMMENT 'Shipment Size s45',
  `size_comp_s46` int(11) NOT NULL COMMENT 'Shipment Size s46',
  `size_comp_s47` int(11) NOT NULL COMMENT 'Shipment Size s47',
  `size_comp_s48` int(11) NOT NULL COMMENT 'Shipment Size s48',
  `size_comp_s49` int(11) NOT NULL COMMENT 'Shipment Size s49',
  `size_comp_s50` int(11) NOT NULL COMMENT 'Shipment Size s50',
  `plan_sec1` int(11) NOT NULL,
  `plan_sec2` int(11) NOT NULL,
  `plan_sec3` int(11) NOT NULL,
  `plan_sec4` int(11) NOT NULL,
  `plan_sec5` int(11) NOT NULL,
  `plan_sec6` int(11) NOT NULL,
  `plan_sec7` int(11) NOT NULL,
  `plan_sec8` int(11) NOT NULL,
  `plan_sec9` int(11) NOT NULL,
  `actu_sec1` int(11) NOT NULL,
  `actu_sec2` int(11) NOT NULL,
  `actu_sec3` int(11) NOT NULL,
  `actu_sec4` int(11) NOT NULL,
  `actu_sec5` int(11) NOT NULL,
  `actu_sec6` int(11) NOT NULL,
  `actu_sec7` int(11) NOT NULL,
  `actu_sec8` int(11) NOT NULL,
  `actu_sec9` int(11) NOT NULL,
  `tid` int(11) NOT NULL AUTO_INCREMENT,
  `remarks` text NOT NULL,
  PRIMARY KEY (`tid`),
  KEY `NewIndex1` (`shipment_plan_id`,`fastreact_plan_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Table structure for table `shipment_plan` */

DROP TABLE IF EXISTS `bai_pro4`.`shipment_plan`;

CREATE TABLE `bai_pro4`.`shipment_plan` (
  `order_no` varchar(10) NOT NULL,
  `delivery_no` varchar(10) NOT NULL,
  `del_status` varchar(2) NOT NULL,
  `mpo` varchar(30) NOT NULL,
  `cpo` varchar(30) NOT NULL,
  `buyer` varchar(36) NOT NULL,
  `product` varchar(40) NOT NULL,
  `buyer_division` varchar(40) NOT NULL,
  `style` varchar(15) NOT NULL,
  `schedule_no` varchar(15) NOT NULL,
  `color` varchar(50) NOT NULL,
  `size` varchar(15) NOT NULL,
  `z_feature` varchar(15) NOT NULL,
  `ord_qty` bigint(20) NOT NULL,
  `ex_factory_date` date NOT NULL,
  `mode` varchar(5) NOT NULL,
  `destination` varchar(10) NOT NULL,
  `packing_method` varchar(6) NOT NULL,
  `fob_price_per_piece` float NOT NULL,
  `cm_value` float NOT NULL,
  `ssc_code` varchar(150) NOT NULL,
  `ship_tid` bigint(20) NOT NULL AUTO_INCREMENT,
  `week_code` tinyint(11) NOT NULL,
  `status` tinyint(11) NOT NULL,
  `ssc_code_new` varchar(200) NOT NULL,
  `order_embl_a` tinyint(11) NOT NULL,
  `order_embl_b` tinyint(11) NOT NULL,
  `order_embl_c` tinyint(11) NOT NULL,
  `order_embl_d` tinyint(11) NOT NULL,
  `order_embl_e` tinyint(11) NOT NULL,
  `order_embl_f` tinyint(11) NOT NULL,
  `order_embl_g` tinyint(11) NOT NULL,
  `order_embl_h` tinyint(11) NOT NULL,
  `ssc_code_week_plan` varchar(250) DEFAULT NULL,
  `cw_check` smallint(6) NOT NULL,
  PRIMARY KEY (`ship_tid`),
  UNIQUE KEY `ssc_code_week_plan` (`ssc_code_week_plan`),
  KEY `NewIndex1` (`buyer_division`,`style`,`schedule_no`,`color`,`size`),
  KEY `NewIndex2` (`buyer_division`),
  KEY `NewIndex3` (`style`,`schedule_no`,`color`),
  KEY `NewIndex4` (`ssc_code`,`ship_tid`),
  KEY `NewIndex5` (`schedule_no`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

/*Table structure for table `shipment_plan_archive` */

DROP TABLE IF EXISTS `bai_pro4`.`shipment_plan_archive`;

CREATE TABLE `bai_pro4`.`shipment_plan_archive` (
  `order_no` varchar(10) NOT NULL,
  `delivery_no` varchar(10) NOT NULL,
  `del_status` varchar(2) NOT NULL,
  `mpo` varchar(30) NOT NULL,
  `cpo` varchar(30) NOT NULL,
  `buyer` varchar(36) NOT NULL,
  `product` varchar(40) NOT NULL,
  `buyer_division` varchar(40) NOT NULL,
  `style` varchar(15) NOT NULL,
  `schedule_no` varchar(15) NOT NULL,
  `color` varchar(50) NOT NULL,
  `size` varchar(15) NOT NULL,
  `z_feature` varchar(15) NOT NULL,
  `ord_qty` bigint(20) NOT NULL,
  `ex_factory_date` date NOT NULL,
  `mode` varchar(5) NOT NULL,
  `destination` varchar(10) NOT NULL,
  `packing_method` varchar(6) NOT NULL,
  `fob_price_per_piece` float NOT NULL,
  `cm_value` float NOT NULL,
  `ssc_code` varchar(150) NOT NULL,
  `ship_tid` bigint(20) NOT NULL AUTO_INCREMENT,
  `week_code` tinyint(11) NOT NULL,
  `status` tinyint(11) NOT NULL,
  `ssc_code_new` varchar(200) NOT NULL,
  `order_embl_a` tinyint(11) NOT NULL,
  `order_embl_b` tinyint(11) NOT NULL,
  `order_embl_c` tinyint(11) NOT NULL,
  `order_embl_d` tinyint(11) NOT NULL,
  `order_embl_e` tinyint(11) NOT NULL,
  `order_embl_f` tinyint(11) NOT NULL,
  `order_embl_g` tinyint(11) NOT NULL,
  `order_embl_h` tinyint(11) NOT NULL,
  `ssc_code_week_plan` varchar(250) DEFAULT NULL,
  `cw_check` smallint(6) NOT NULL,
  PRIMARY KEY (`ship_tid`),
  UNIQUE KEY `ssc_code_week_plan` (`ssc_code_week_plan`),
  KEY `schedule_no` (`schedule_no`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Table structure for table `shipment_plan_ref_view` */

DROP TABLE IF EXISTS `bai_pro4`.`shipment_plan_ref_view`;

CREATE TABLE `bai_pro4`.`shipment_plan_ref_view` (
  `order_no` varchar(30) DEFAULT NULL,
  `delivery_no` varchar(30) DEFAULT NULL,
  `del_status` varchar(6) DEFAULT NULL,
  `mpo` varchar(90) DEFAULT NULL,
  `cpo` varchar(90) DEFAULT NULL,
  `buyer` varchar(108) DEFAULT NULL,
  `product` varchar(120) DEFAULT NULL,
  `buyer_division` varchar(120) DEFAULT NULL,
  `style` varchar(45) DEFAULT NULL,
  `schedule_no` varchar(45) DEFAULT NULL,
  `color` varchar(150) DEFAULT NULL,
  `size` varchar(45) DEFAULT NULL,
  `z_feature` varchar(45) DEFAULT NULL,
  `ord_qty` double DEFAULT NULL,
  `ex_factory_date` date DEFAULT NULL,
  `mode` varchar(15) DEFAULT NULL,
  `destination` varchar(30) DEFAULT NULL,
  `packing_method` varchar(18) DEFAULT NULL,
  `fob_price_per_piece` float DEFAULT NULL,
  `cm_value` float DEFAULT NULL,
  `ssc_code` varchar(450) DEFAULT NULL,
  `ship_tid` double DEFAULT NULL,
  `week_code` tinyint(11) DEFAULT NULL,
  `status` tinyint(11) DEFAULT NULL,
  `ssc_code_new` varchar(600) DEFAULT NULL,
  `order_embl_a` tinyint(11) DEFAULT NULL,
  `order_embl_b` tinyint(11) DEFAULT NULL,
  `order_embl_c` tinyint(11) DEFAULT NULL,
  `order_embl_d` tinyint(11) DEFAULT NULL,
  `order_embl_e` tinyint(11) DEFAULT NULL,
  `order_embl_f` tinyint(11) DEFAULT NULL,
  `order_embl_g` tinyint(11) DEFAULT NULL,
  `order_embl_h` tinyint(11) DEFAULT NULL,
  `ord_qty_new` decimal(42,0) DEFAULT NULL,
  KEY `NewIndex1` (`style`,`schedule_no`,`color`),
  KEY `NewIndex2` (`style`,`schedule_no`,`color`,`size`),
  KEY `NewIndex3` (`ship_tid`),
  KEY `NewIndex4` (`buyer_division`,`style`,`schedule_no`,`color`,`size`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Table structure for table `week_del_log` */

DROP TABLE IF EXISTS `bai_pro4`.`week_del_log`;

CREATE TABLE `bai_pro4`.`week_del_log` (
  `ex_fact` date NOT NULL,
  `log_time` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `ship_tid` int(11) NOT NULL,
  `ref_id` int(11) NOT NULL,
  KEY `NewIndex1` (`ex_fact`,`ship_tid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `week_delivery_plan` */

DROP TABLE IF EXISTS `bai_pro4`.`week_delivery_plan`;

CREATE TABLE `bai_pro4`.`week_delivery_plan` (
  `shipment_plan_id` int(11) NOT NULL,
  `fastreact_plan_id` int(11) NOT NULL,
  `size_code` varchar(50) DEFAULT NULL,
  `size_xs` mediumint(9) NOT NULL DEFAULT 0,
  `size_s` mediumint(9) NOT NULL DEFAULT 0,
  `size_m` mediumint(9) NOT NULL DEFAULT 0,
  `size_l` mediumint(9) NOT NULL DEFAULT 0,
  `size_xl` mediumint(9) NOT NULL DEFAULT 0,
  `size_xxl` mediumint(9) NOT NULL DEFAULT 0,
  `size_xxxl` mediumint(9) NOT NULL DEFAULT 0,
  `size_s01` int(11) NOT NULL DEFAULT 0,
  `size_s02` int(11) NOT NULL DEFAULT 0,
  `size_s03` int(11) NOT NULL DEFAULT 0,
  `size_s04` int(11) NOT NULL DEFAULT 0,
  `size_s05` int(11) NOT NULL DEFAULT 0,
  `size_s06` mediumint(9) NOT NULL DEFAULT 0,
  `size_s07` int(11) NOT NULL DEFAULT 0,
  `size_s08` mediumint(9) NOT NULL DEFAULT 0,
  `size_s09` int(11) NOT NULL DEFAULT 0,
  `size_s10` mediumint(9) NOT NULL DEFAULT 0,
  `size_s11` int(11) NOT NULL DEFAULT 0,
  `size_s12` mediumint(9) NOT NULL DEFAULT 0,
  `size_s13` int(11) NOT NULL DEFAULT 0,
  `size_s14` mediumint(9) NOT NULL DEFAULT 0,
  `size_s15` int(11) NOT NULL DEFAULT 0,
  `size_s16` mediumint(9) NOT NULL DEFAULT 0,
  `size_s17` int(11) NOT NULL DEFAULT 0,
  `size_s18` mediumint(9) NOT NULL DEFAULT 0,
  `size_s19` int(11) NOT NULL DEFAULT 0,
  `size_s20` mediumint(9) NOT NULL DEFAULT 0,
  `size_s21` int(11) NOT NULL DEFAULT 0,
  `size_s22` mediumint(9) NOT NULL DEFAULT 0,
  `size_s23` int(11) NOT NULL DEFAULT 0,
  `size_s24` mediumint(9) NOT NULL DEFAULT 0,
  `size_s25` int(11) NOT NULL DEFAULT 0,
  `size_s26` mediumint(9) NOT NULL DEFAULT 0,
  `size_s27` int(11) NOT NULL DEFAULT 0,
  `size_s28` mediumint(9) NOT NULL DEFAULT 0,
  `size_s29` int(11) NOT NULL DEFAULT 0,
  `size_s30` mediumint(9) NOT NULL DEFAULT 0,
  `size_s31` int(11) NOT NULL DEFAULT 0,
  `size_s32` int(11) NOT NULL DEFAULT 0,
  `size_s33` int(11) NOT NULL DEFAULT 0,
  `size_s34` int(11) NOT NULL DEFAULT 0,
  `size_s35` int(11) NOT NULL DEFAULT 0,
  `size_s36` int(11) NOT NULL DEFAULT 0,
  `size_s37` int(11) NOT NULL DEFAULT 0,
  `size_s38` int(11) NOT NULL DEFAULT 0,
  `size_s39` int(11) NOT NULL DEFAULT 0,
  `size_s40` int(11) NOT NULL DEFAULT 0,
  `size_s41` int(11) NOT NULL DEFAULT 0,
  `size_s42` int(11) NOT NULL DEFAULT 0,
  `size_s43` int(11) NOT NULL DEFAULT 0,
  `size_s44` int(11) NOT NULL DEFAULT 0,
  `size_s45` int(11) NOT NULL DEFAULT 0,
  `size_s46` int(11) NOT NULL DEFAULT 0,
  `size_s47` int(11) NOT NULL DEFAULT 0,
  `size_s48` int(11) NOT NULL DEFAULT 0,
  `size_s49` int(11) NOT NULL DEFAULT 0,
  `size_s50` int(11) NOT NULL DEFAULT 0,
  `plan_start_date` date NOT NULL,
  `plan_comp_date` date NOT NULL,
  `size_comp_xs` mediumint(9) NOT NULL DEFAULT 0,
  `size_comp_s` mediumint(9) NOT NULL DEFAULT 0,
  `size_comp_m` mediumint(9) NOT NULL DEFAULT 0,
  `size_comp_l` mediumint(9) NOT NULL DEFAULT 0,
  `size_comp_xl` mediumint(9) NOT NULL DEFAULT 0,
  `size_comp_xxl` mediumint(9) NOT NULL DEFAULT 0,
  `size_comp_xxxl` mediumint(9) NOT NULL DEFAULT 0,
  `size_comp_s01` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s01',
  `size_comp_s02` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s02',
  `size_comp_s03` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s03',
  `size_comp_s04` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s04',
  `size_comp_s05` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s05',
  `size_comp_s06` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s06',
  `size_comp_s07` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s07',
  `size_comp_s08` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s08',
  `size_comp_s09` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s09',
  `size_comp_s10` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s10',
  `size_comp_s11` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s11',
  `size_comp_s12` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s12',
  `size_comp_s13` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s13',
  `size_comp_s14` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s14',
  `size_comp_s15` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s15',
  `size_comp_s16` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s16',
  `size_comp_s17` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s17',
  `size_comp_s18` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s18',
  `size_comp_s19` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s19',
  `size_comp_s20` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s20',
  `size_comp_s21` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s21',
  `size_comp_s22` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s22',
  `size_comp_s23` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s23',
  `size_comp_s24` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s24',
  `size_comp_s25` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s25',
  `size_comp_s26` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s26',
  `size_comp_s27` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s27',
  `size_comp_s28` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s28',
  `size_comp_s29` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s29',
  `size_comp_s30` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s30',
  `size_comp_s31` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s31',
  `size_comp_s32` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s32',
  `size_comp_s33` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s33',
  `size_comp_s34` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s34',
  `size_comp_s35` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s35',
  `size_comp_s36` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s36',
  `size_comp_s37` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s37',
  `size_comp_s38` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s38',
  `size_comp_s39` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s39',
  `size_comp_s40` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s40',
  `size_comp_s41` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s41',
  `size_comp_s42` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s42',
  `size_comp_s43` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s43',
  `size_comp_s44` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s44',
  `size_comp_s45` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s45',
  `size_comp_s46` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s46',
  `size_comp_s47` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s47',
  `size_comp_s48` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s48',
  `size_comp_s49` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s49',
  `size_comp_s50` mediumint(9) NOT NULL DEFAULT 0 COMMENT 'Size s50',
  `plan_sec1` mediumint(9) NOT NULL DEFAULT 0,
  `plan_sec2` mediumint(9) NOT NULL DEFAULT 0,
  `plan_sec3` mediumint(9) NOT NULL DEFAULT 0,
  `plan_sec4` mediumint(9) NOT NULL DEFAULT 0,
  `plan_sec5` mediumint(9) NOT NULL DEFAULT 0,
  `plan_sec6` mediumint(9) NOT NULL DEFAULT 0,
  `plan_sec7` mediumint(9) NOT NULL DEFAULT 0,
  `plan_sec8` mediumint(9) NOT NULL DEFAULT 0,
  `plan_sec9` mediumint(9) NOT NULL DEFAULT 0,
  `plan_sec10` mediumint(9) NOT NULL DEFAULT 0,
  `plan_sec11` mediumint(9) NOT NULL DEFAULT 0,
  `plan_sec12` mediumint(9) NOT NULL DEFAULT 0,
  `plan_sec13` mediumint(9) NOT NULL DEFAULT 0,
  `plan_sec14` mediumint(9) NOT NULL DEFAULT 0,
  `plan_sec15` mediumint(9) NOT NULL DEFAULT 0,
  `actu_sec1` mediumint(9) NOT NULL DEFAULT 0,
  `actu_sec2` mediumint(9) NOT NULL DEFAULT 0,
  `actu_sec3` mediumint(9) NOT NULL DEFAULT 0,
  `actu_sec4` mediumint(9) NOT NULL DEFAULT 0,
  `actu_sec5` mediumint(9) NOT NULL DEFAULT 0,
  `actu_sec6` mediumint(9) NOT NULL DEFAULT 0,
  `actu_sec7` mediumint(9) NOT NULL DEFAULT 0,
  `actu_sec8` mediumint(9) NOT NULL DEFAULT 0,
  `actu_sec9` mediumint(9) NOT NULL DEFAULT 0,
  `actu_sec10` mediumint(9) NOT NULL DEFAULT 0,
  `actu_sec11` mediumint(9) NOT NULL DEFAULT 0,
  `actu_sec12` mediumint(9) NOT NULL DEFAULT 0,
  `actu_sec13` mediumint(9) NOT NULL DEFAULT 0,
  `actu_sec14` mediumint(9) NOT NULL DEFAULT 0,
  `actu_sec15` mediumint(9) NOT NULL DEFAULT 0,
  `tid` mediumint(9) NOT NULL DEFAULT 0,
  `remarks` text NOT NULL COMMENT 'Planner Remarks^Packing Remarks^Commitments (ABC)',
  `ref_id` int(11) NOT NULL AUTO_INCREMENT,
  `rev_exfactory` date NOT NULL DEFAULT '0000-00-00',
  `rev_emb_status` varchar(100) DEFAULT NULL,
  `act_cut` mediumint(9) NOT NULL,
  `act_in` mediumint(9) NOT NULL,
  `act_fca` mediumint(9) NOT NULL,
  `act_mca` mediumint(9) NOT NULL,
  `act_fg` mediumint(9) NOT NULL,
  `cart_pending` mediumint(9) NOT NULL,
  `priority` mediumint(9) NOT NULL,
  `original_order_qty` mediumint(9) NOT NULL,
  `rev_mode` varchar(30) NOT NULL,
  `act_ship` mediumint(9) NOT NULL,
  `act_exfact` date NOT NULL,
  `act_rej` int(11) NOT NULL COMMENT 'actual rejections',
  PRIMARY KEY (`ref_id`),
  KEY `shipment_plan_id` (`shipment_plan_id`,`fastreact_plan_id`,`tid`,`ref_id`),
  KEY `new` (`shipment_plan_id`,`fastreact_plan_id`,`rev_exfactory`),
  KEY `NewIndex1` (`shipment_plan_id`,`fastreact_plan_id`,`size_code`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

/*Table structure for table `week_delivery_plan_archive` */

DROP TABLE IF EXISTS `bai_pro4`.`week_delivery_plan_archive`;

CREATE TABLE `bai_pro4`.`week_delivery_plan_archive` (
  `shipment_plan_id` int(11) NOT NULL,
  `fastreact_plan_id` int(11) NOT NULL,
  `size_xs` mediumint(9) NOT NULL,
  `size_s` mediumint(9) NOT NULL,
  `size_m` mediumint(9) NOT NULL,
  `size_l` mediumint(9) NOT NULL,
  `size_xl` mediumint(9) NOT NULL,
  `size_xxl` mediumint(9) NOT NULL,
  `size_xxxl` mediumint(9) NOT NULL,
  `size_s01` int(11) NOT NULL,
  `size_s02` int(11) NOT NULL,
  `size_s03` int(11) NOT NULL,
  `size_s04` int(11) NOT NULL,
  `size_s05` int(11) NOT NULL,
  `size_s06` mediumint(9) NOT NULL,
  `size_s07` int(11) NOT NULL,
  `size_s08` mediumint(9) NOT NULL,
  `size_s09` int(11) NOT NULL,
  `size_s10` mediumint(9) NOT NULL,
  `size_s11` int(11) NOT NULL,
  `size_s12` mediumint(9) NOT NULL,
  `size_s13` int(11) NOT NULL,
  `size_s14` mediumint(9) NOT NULL,
  `size_s15` int(11) NOT NULL,
  `size_s16` mediumint(9) NOT NULL,
  `size_s17` int(11) NOT NULL,
  `size_s18` mediumint(9) NOT NULL,
  `size_s19` int(11) NOT NULL,
  `size_s20` mediumint(9) NOT NULL,
  `size_s21` int(11) NOT NULL,
  `size_s22` mediumint(9) NOT NULL,
  `size_s23` int(11) NOT NULL,
  `size_s24` mediumint(9) NOT NULL,
  `size_s25` int(11) NOT NULL,
  `size_s26` mediumint(9) NOT NULL,
  `size_s27` int(11) NOT NULL,
  `size_s28` mediumint(9) NOT NULL,
  `size_s29` int(11) NOT NULL,
  `size_s30` mediumint(9) NOT NULL,
  `size_s31` int(11) NOT NULL,
  `size_s32` int(11) NOT NULL,
  `size_s33` int(11) NOT NULL,
  `size_s34` int(11) NOT NULL,
  `size_s35` int(11) NOT NULL,
  `size_s36` int(11) NOT NULL,
  `size_s37` int(11) NOT NULL,
  `size_s38` int(11) NOT NULL,
  `size_s39` int(11) NOT NULL,
  `size_s40` int(11) NOT NULL,
  `size_s41` int(11) NOT NULL,
  `size_s42` int(11) NOT NULL,
  `size_s43` int(11) NOT NULL,
  `size_s44` int(11) NOT NULL,
  `size_s45` int(11) NOT NULL,
  `size_s46` int(11) NOT NULL,
  `size_s47` int(11) NOT NULL,
  `size_s48` int(11) NOT NULL,
  `size_s49` int(11) NOT NULL,
  `size_s50` int(11) NOT NULL,
  `plan_start_date` date NOT NULL,
  `plan_comp_date` date NOT NULL,
  `size_comp_xs` mediumint(9) NOT NULL,
  `size_comp_s` mediumint(9) NOT NULL,
  `size_comp_m` mediumint(9) NOT NULL,
  `size_comp_l` mediumint(9) NOT NULL,
  `size_comp_xl` mediumint(9) NOT NULL,
  `size_comp_xxl` mediumint(9) NOT NULL,
  `size_comp_xxxl` mediumint(9) NOT NULL,
  `size_comp_s01` mediumint(9) NOT NULL COMMENT 'Size s01',
  `size_comp_s02` mediumint(9) NOT NULL COMMENT 'Size s02',
  `size_comp_s03` mediumint(9) NOT NULL COMMENT 'Size s03',
  `size_comp_s04` mediumint(9) NOT NULL COMMENT 'Size s04',
  `size_comp_s05` mediumint(9) NOT NULL COMMENT 'Size s05',
  `size_comp_s06` mediumint(9) NOT NULL COMMENT 'Size s06',
  `size_comp_s07` mediumint(9) NOT NULL COMMENT 'Size s07',
  `size_comp_s08` mediumint(9) NOT NULL COMMENT 'Size s08',
  `size_comp_s09` mediumint(9) NOT NULL COMMENT 'Size s09',
  `size_comp_s10` mediumint(9) NOT NULL COMMENT 'Size s10',
  `size_comp_s11` mediumint(9) NOT NULL COMMENT 'Size s11',
  `size_comp_s12` mediumint(9) NOT NULL COMMENT 'Size s12',
  `size_comp_s13` mediumint(9) NOT NULL COMMENT 'Size s13',
  `size_comp_s14` mediumint(9) NOT NULL COMMENT 'Size s14',
  `size_comp_s15` mediumint(9) NOT NULL COMMENT 'Size s15',
  `size_comp_s16` mediumint(9) NOT NULL COMMENT 'Size s16',
  `size_comp_s17` mediumint(9) NOT NULL COMMENT 'Size s17',
  `size_comp_s18` mediumint(9) NOT NULL COMMENT 'Size s18',
  `size_comp_s19` mediumint(9) NOT NULL COMMENT 'Size s19',
  `size_comp_s20` mediumint(9) NOT NULL COMMENT 'Size s20',
  `size_comp_s21` mediumint(9) NOT NULL COMMENT 'Size s21',
  `size_comp_s22` mediumint(9) NOT NULL COMMENT 'Size s22',
  `size_comp_s23` mediumint(9) NOT NULL COMMENT 'Size s23',
  `size_comp_s24` mediumint(9) NOT NULL COMMENT 'Size s24',
  `size_comp_s25` mediumint(9) NOT NULL COMMENT 'Size s25',
  `size_comp_s26` mediumint(9) NOT NULL COMMENT 'Size s26',
  `size_comp_s27` mediumint(9) NOT NULL COMMENT 'Size s27',
  `size_comp_s28` mediumint(9) NOT NULL COMMENT 'Size s28',
  `size_comp_s29` mediumint(9) NOT NULL COMMENT 'Size s29',
  `size_comp_s30` mediumint(9) NOT NULL COMMENT 'Size s30',
  `size_comp_s31` mediumint(9) NOT NULL COMMENT 'Size s31',
  `size_comp_s32` mediumint(9) NOT NULL COMMENT 'Size s32',
  `size_comp_s33` mediumint(9) NOT NULL COMMENT 'Size s33',
  `size_comp_s34` mediumint(9) NOT NULL COMMENT 'Size s34',
  `size_comp_s35` mediumint(9) NOT NULL COMMENT 'Size s35',
  `size_comp_s36` mediumint(9) NOT NULL COMMENT 'Size s36',
  `size_comp_s37` mediumint(9) NOT NULL COMMENT 'Size s37',
  `size_comp_s38` mediumint(9) NOT NULL COMMENT 'Size s38',
  `size_comp_s39` mediumint(9) NOT NULL COMMENT 'Size s39',
  `size_comp_s40` mediumint(9) NOT NULL COMMENT 'Size s40',
  `size_comp_s41` mediumint(9) NOT NULL COMMENT 'Size s41',
  `size_comp_s42` mediumint(9) NOT NULL COMMENT 'Size s42',
  `size_comp_s43` mediumint(9) NOT NULL COMMENT 'Size s43',
  `size_comp_s44` mediumint(9) NOT NULL COMMENT 'Size s44',
  `size_comp_s45` mediumint(9) NOT NULL COMMENT 'Size s45',
  `size_comp_s46` mediumint(9) NOT NULL COMMENT 'Size s46',
  `size_comp_s47` mediumint(9) NOT NULL COMMENT 'Size s47',
  `size_comp_s48` mediumint(9) NOT NULL COMMENT 'Size s48',
  `size_comp_s49` mediumint(9) NOT NULL COMMENT 'Size s49',
  `size_comp_s50` mediumint(9) NOT NULL COMMENT 'Size s50',
  `plan_sec1` mediumint(9) NOT NULL,
  `plan_sec2` mediumint(9) NOT NULL,
  `plan_sec3` mediumint(9) NOT NULL,
  `plan_sec4` mediumint(9) NOT NULL,
  `plan_sec5` mediumint(9) NOT NULL,
  `plan_sec6` mediumint(9) NOT NULL,
  `plan_sec7` mediumint(9) NOT NULL,
  `plan_sec8` mediumint(9) NOT NULL,
  `plan_sec9` mediumint(9) NOT NULL,
  `actu_sec1` mediumint(9) NOT NULL,
  `actu_sec2` mediumint(9) NOT NULL,
  `actu_sec3` mediumint(9) NOT NULL,
  `actu_sec4` mediumint(9) NOT NULL,
  `actu_sec5` mediumint(9) NOT NULL,
  `actu_sec6` mediumint(9) NOT NULL,
  `actu_sec7` mediumint(9) NOT NULL,
  `actu_sec8` mediumint(9) NOT NULL,
  `actu_sec9` mediumint(9) NOT NULL,
  `tid` mediumint(9) NOT NULL,
  `remarks` text NOT NULL COMMENT 'Planner Remarks^Packing Remarks^Commitments (ABC)',
  `ref_id` int(11) NOT NULL AUTO_INCREMENT,
  `rev_exfactory` date DEFAULT NULL,
  `rev_emb_status` varchar(100) DEFAULT NULL,
  `act_cut` mediumint(9) NOT NULL,
  `act_in` mediumint(9) NOT NULL,
  `act_fca` mediumint(9) NOT NULL,
  `act_mca` mediumint(9) NOT NULL,
  `act_fg` mediumint(9) NOT NULL,
  `cart_pending` mediumint(9) NOT NULL,
  `priority` mediumint(9) NOT NULL,
  `original_order_qty` mediumint(9) NOT NULL,
  `rev_mode` varchar(30) NOT NULL,
  `act_ship` mediumint(9) NOT NULL,
  `act_exfact` date NOT NULL,
  `act_rej` int(11) NOT NULL COMMENT 'To update actual rejections',
  PRIMARY KEY (`ref_id`),
  KEY `shipment_plan_id` (`shipment_plan_id`,`fastreact_plan_id`,`tid`,`ref_id`),
  KEY `new` (`shipment_plan_id`,`fastreact_plan_id`,`rev_exfactory`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Table structure for table `week_delivery_plan_ref_temp` */

DROP TABLE IF EXISTS `bai_pro4`.`week_delivery_plan_ref_temp`;

CREATE TABLE `bai_pro4`.`week_delivery_plan_ref_temp` (
  `ship_tid` double DEFAULT NULL,
  `tid` int(11) DEFAULT NULL,
  `buyer_division` varchar(120) DEFAULT NULL,
  `schedule_no` varchar(45) DEFAULT NULL,
  `color` varchar(150) DEFAULT NULL,
  `style` varchar(45) DEFAULT NULL,
  `size` varchar(25) DEFAULT NULL,
  `ord_qty_new` int(11) DEFAULT NULL,
  `ord_qty_new_old` decimal(42,0) DEFAULT NULL,
  `m3_ship_plan_ex_fact` date DEFAULT NULL,
  `ex_factory_date` date DEFAULT NULL,
  `rev_exfactory` date DEFAULT NULL,
  `ex_factory_date_new` date DEFAULT NULL,
  `output` double DEFAULT NULL,
  `act_cut` int(11) DEFAULT NULL,
  `act_in` int(11) DEFAULT NULL,
  `act_fca` int(11) DEFAULT NULL,
  `act_mca` int(11) DEFAULT NULL,
  `act_fg` int(11) DEFAULT NULL,
  `act_ship` int(11) DEFAULT NULL,
  `cart_pending` int(11) DEFAULT NULL,
  `priority` int(11) DEFAULT NULL,
  `ref_id` double DEFAULT NULL,
  `act_exfact` date DEFAULT NULL,
  `act_rej` int(11) DEFAULT NULL,
  `remarks` varchar(500) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Table structure for table `week_delivery_plan_temp` */

DROP TABLE IF EXISTS `bai_pro4`.`week_delivery_plan_temp`;

CREATE TABLE `bai_pro4`.`week_delivery_plan_temp` (
  `shipment_plan_id` int(11) NOT NULL,
  `fastreact_plan_id` int(11) NOT NULL,
  `size_code` varchar(50) DEFAULT NULL,
  `size_xs` mediumint(9) NOT NULL,
  `size_s` mediumint(9) NOT NULL,
  `size_m` mediumint(9) NOT NULL,
  `size_l` mediumint(9) NOT NULL,
  `size_xl` mediumint(9) NOT NULL,
  `size_xxl` mediumint(9) NOT NULL,
  `size_xxxl` mediumint(9) NOT NULL,
  `size_s01` int(11) NOT NULL,
  `size_s02` int(11) NOT NULL,
  `size_s03` int(11) NOT NULL,
  `size_s04` int(11) NOT NULL,
  `size_s05` int(11) NOT NULL,
  `size_s06` mediumint(9) NOT NULL,
  `size_s07` int(11) NOT NULL,
  `size_s08` mediumint(9) NOT NULL,
  `size_s09` int(11) NOT NULL,
  `size_s10` mediumint(9) NOT NULL,
  `size_s11` int(11) NOT NULL,
  `size_s12` mediumint(9) NOT NULL,
  `size_s13` int(11) NOT NULL,
  `size_s14` mediumint(9) NOT NULL,
  `size_s15` int(11) NOT NULL,
  `size_s16` mediumint(9) NOT NULL,
  `size_s17` int(11) NOT NULL,
  `size_s18` mediumint(9) NOT NULL,
  `size_s19` int(11) NOT NULL,
  `size_s20` mediumint(9) NOT NULL,
  `size_s21` int(11) NOT NULL,
  `size_s22` mediumint(9) NOT NULL,
  `size_s23` int(11) NOT NULL,
  `size_s24` mediumint(9) NOT NULL,
  `size_s25` int(11) NOT NULL,
  `size_s26` mediumint(9) NOT NULL,
  `size_s27` int(11) NOT NULL,
  `size_s28` mediumint(9) NOT NULL,
  `size_s29` int(11) NOT NULL,
  `size_s30` mediumint(9) NOT NULL,
  `size_s31` int(11) NOT NULL,
  `size_s32` int(11) NOT NULL,
  `size_s33` int(11) NOT NULL,
  `size_s34` int(11) NOT NULL,
  `size_s35` int(11) NOT NULL,
  `size_s36` int(11) NOT NULL,
  `size_s37` int(11) NOT NULL,
  `size_s38` int(11) NOT NULL,
  `size_s39` int(11) NOT NULL,
  `size_s40` int(11) NOT NULL,
  `size_s41` int(11) NOT NULL,
  `size_s42` int(11) NOT NULL,
  `size_s43` int(11) NOT NULL,
  `size_s44` int(11) NOT NULL,
  `size_s45` int(11) NOT NULL,
  `size_s46` int(11) NOT NULL,
  `size_s47` int(11) NOT NULL,
  `size_s48` int(11) NOT NULL,
  `size_s49` int(11) NOT NULL,
  `size_s50` int(11) NOT NULL,
  `plan_start_date` date NOT NULL,
  `plan_comp_date` date NOT NULL,
  `size_comp_xs` mediumint(9) NOT NULL,
  `size_comp_s` mediumint(9) NOT NULL,
  `size_comp_m` mediumint(9) NOT NULL,
  `size_comp_l` mediumint(9) NOT NULL,
  `size_comp_xl` mediumint(9) NOT NULL,
  `size_comp_xxl` mediumint(9) NOT NULL,
  `size_comp_xxxl` mediumint(9) NOT NULL,
  `size_comp_s01` mediumint(9) NOT NULL COMMENT 'Size s01',
  `size_comp_s02` mediumint(9) NOT NULL COMMENT 'Size s02',
  `size_comp_s03` mediumint(9) NOT NULL COMMENT 'Size s03',
  `size_comp_s04` mediumint(9) NOT NULL COMMENT 'Size s04',
  `size_comp_s05` mediumint(9) NOT NULL COMMENT 'Size s05',
  `size_comp_s06` mediumint(9) NOT NULL COMMENT 'Size s06',
  `size_comp_s07` mediumint(9) NOT NULL COMMENT 'Size s07',
  `size_comp_s08` mediumint(9) NOT NULL COMMENT 'Size s08',
  `size_comp_s09` mediumint(9) NOT NULL COMMENT 'Size s09',
  `size_comp_s10` mediumint(9) NOT NULL COMMENT 'Size s10',
  `size_comp_s11` mediumint(9) NOT NULL COMMENT 'Size s11',
  `size_comp_s12` mediumint(9) NOT NULL COMMENT 'Size s12',
  `size_comp_s13` mediumint(9) NOT NULL COMMENT 'Size s13',
  `size_comp_s14` mediumint(9) NOT NULL COMMENT 'Size s14',
  `size_comp_s15` mediumint(9) NOT NULL COMMENT 'Size s15',
  `size_comp_s16` mediumint(9) NOT NULL COMMENT 'Size s16',
  `size_comp_s17` mediumint(9) NOT NULL COMMENT 'Size s17',
  `size_comp_s18` mediumint(9) NOT NULL COMMENT 'Size s18',
  `size_comp_s19` mediumint(9) NOT NULL COMMENT 'Size s19',
  `size_comp_s20` mediumint(9) NOT NULL COMMENT 'Size s20',
  `size_comp_s21` mediumint(9) NOT NULL COMMENT 'Size s21',
  `size_comp_s22` mediumint(9) NOT NULL COMMENT 'Size s22',
  `size_comp_s23` mediumint(9) NOT NULL COMMENT 'Size s23',
  `size_comp_s24` mediumint(9) NOT NULL COMMENT 'Size s24',
  `size_comp_s25` mediumint(9) NOT NULL COMMENT 'Size s25',
  `size_comp_s26` mediumint(9) NOT NULL COMMENT 'Size s26',
  `size_comp_s27` mediumint(9) NOT NULL COMMENT 'Size s27',
  `size_comp_s28` mediumint(9) NOT NULL COMMENT 'Size s28',
  `size_comp_s29` mediumint(9) NOT NULL COMMENT 'Size s29',
  `size_comp_s30` mediumint(9) NOT NULL COMMENT 'Size s30',
  `size_comp_s31` mediumint(9) NOT NULL COMMENT 'Size s31',
  `size_comp_s32` mediumint(9) NOT NULL COMMENT 'Size s32',
  `size_comp_s33` mediumint(9) NOT NULL COMMENT 'Size s33',
  `size_comp_s34` mediumint(9) NOT NULL COMMENT 'Size s34',
  `size_comp_s35` mediumint(9) NOT NULL COMMENT 'Size s35',
  `size_comp_s36` mediumint(9) NOT NULL COMMENT 'Size s36',
  `size_comp_s37` mediumint(9) NOT NULL COMMENT 'Size s37',
  `size_comp_s38` mediumint(9) NOT NULL COMMENT 'Size s38',
  `size_comp_s39` mediumint(9) NOT NULL COMMENT 'Size s39',
  `size_comp_s40` mediumint(9) NOT NULL COMMENT 'Size s40',
  `size_comp_s41` mediumint(9) NOT NULL COMMENT 'Size s41',
  `size_comp_s42` mediumint(9) NOT NULL COMMENT 'Size s42',
  `size_comp_s43` mediumint(9) NOT NULL COMMENT 'Size s43',
  `size_comp_s44` mediumint(9) NOT NULL COMMENT 'Size s44',
  `size_comp_s45` mediumint(9) NOT NULL COMMENT 'Size s45',
  `size_comp_s46` mediumint(9) NOT NULL COMMENT 'Size s46',
  `size_comp_s47` mediumint(9) NOT NULL COMMENT 'Size s47',
  `size_comp_s48` mediumint(9) NOT NULL COMMENT 'Size s48',
  `size_comp_s49` mediumint(9) NOT NULL COMMENT 'Size s49',
  `size_comp_s50` mediumint(9) NOT NULL COMMENT 'Size s50',
  `plan_sec1` mediumint(9) NOT NULL,
  `plan_sec2` mediumint(9) NOT NULL,
  `plan_sec3` mediumint(9) NOT NULL,
  `plan_sec4` mediumint(9) NOT NULL,
  `plan_sec5` mediumint(9) NOT NULL,
  `plan_sec6` mediumint(9) NOT NULL,
  `plan_sec7` mediumint(9) NOT NULL,
  `plan_sec8` mediumint(9) NOT NULL,
  `plan_sec9` mediumint(9) NOT NULL,
  `actu_sec1` mediumint(9) NOT NULL,
  `actu_sec2` mediumint(9) NOT NULL,
  `actu_sec3` mediumint(9) NOT NULL,
  `actu_sec4` mediumint(9) NOT NULL,
  `actu_sec5` mediumint(9) NOT NULL,
  `actu_sec6` mediumint(9) NOT NULL,
  `actu_sec7` mediumint(9) NOT NULL,
  `actu_sec8` mediumint(9) NOT NULL,
  `actu_sec9` mediumint(9) NOT NULL,
  `tid` mediumint(9) NOT NULL,
  `remarks` text NOT NULL COMMENT 'Planner Remarks^Packing Remarks^Commitments (ABC)',
  `ref_id` int(11) NOT NULL AUTO_INCREMENT,
  `rev_exfactory` date DEFAULT NULL,
  `rev_emb_status` varchar(100) DEFAULT NULL,
  `act_cut` mediumint(9) NOT NULL,
  `act_in` mediumint(9) NOT NULL,
  `act_fca` mediumint(9) NOT NULL,
  `act_mca` mediumint(9) NOT NULL,
  `act_fg` mediumint(9) NOT NULL,
  `cart_pending` mediumint(9) NOT NULL,
  `priority` mediumint(9) NOT NULL,
  `original_order_qty` mediumint(9) NOT NULL,
  `rev_mode` varchar(30) NOT NULL,
  `act_ship` mediumint(9) NOT NULL,
  `act_exfact` date NOT NULL,
  `act_rej` int(11) NOT NULL COMMENT 'actual rejections',
  PRIMARY KEY (`ref_id`),
  KEY `shipment_plan_id` (`shipment_plan_id`,`fastreact_plan_id`,`tid`,`ref_id`),
  KEY `new` (`shipment_plan_id`,`fastreact_plan_id`,`rev_exfactory`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Table structure for table `weekly_cap_reasons` */

DROP TABLE IF EXISTS `bai_pro4`.`weekly_cap_reasons`;

CREATE TABLE `bai_pro4`.`weekly_cap_reasons` (
  `sno` int(11) NOT NULL AUTO_INCREMENT COMMENT 'primary key',
  `reason` varchar(50) NOT NULL COMMENT 'Planning Remarks',
  `color_code` varchar(10) NOT NULL COMMENT 'Color Identification Of Reason',
  `category` int(11) NOT NULL COMMENT '1-Planning',
  PRIMARY KEY (`sno`),
  UNIQUE KEY `Reason` (`reason`),
  KEY `NewIndex1` (`reason`,`category`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `weekly_delivery_plan_remarks` */

DROP TABLE IF EXISTS `bai_pro4`.`weekly_delivery_plan_remarks`;

CREATE TABLE `bai_pro4`.`weekly_delivery_plan_remarks` (
  `tid` bigint(20) NOT NULL AUTO_INCREMENT,
  `schedule_no` varchar(25) DEFAULT NULL,
  `color_des` varchar(50) DEFAULT NULL,
  `size_ref` varchar(10) DEFAULT NULL,
  `ref_id` varchar(15) DEFAULT NULL,
  `planning_remarks` int(11) DEFAULT NULL,
  `commitments` varchar(100) DEFAULT NULL,
  `remarks` varchar(100) DEFAULT NULL,
  `ex_factory_date` date DEFAULT NULL,
  PRIMARY KEY (`tid`),
  KEY `NewIndex1` (`schedule_no`,`color_des`,`size_ref`),
  KEY `NewIndex2` (`ref_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `weekly_delivery_status_finishing` */

DROP TABLE IF EXISTS `bai_pro4`.`weekly_delivery_status_finishing`;

CREATE TABLE `bai_pro4`.`weekly_delivery_status_finishing` (
  `tid` double NOT NULL,
  `tran_tid` double NOT NULL,
  `buyer` varchar(50) NOT NULL,
  `style` varchar(50) NOT NULL,
  `schedule` double NOT NULL,
  `color` varchar(100) NOT NULL,
  `low_status` varchar(50) NOT NULL,
  `status` varchar(50) NOT NULL,
  `ex_fact` date NOT NULL,
  `log_time` longtext NOT NULL,
  `offered_status` tinytext NOT NULL,
  `dispatch_status` tinytext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
