/*#1260*/;

insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('1','3','Addtional Cut Panel Transaction Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('2','4','CAD Savings Report - Exfactory','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('3','5','CAD Savings Report - Schedule','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('4','6','CAD Savings Report - Style','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('5','7','Consumption Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('6','8','Cutting Status Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('7','9','Fabric Saving Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('8','10','Input Availability Forecast Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('9','11','Input Status Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('10','12','KPI Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('11','13','Recut Detail Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('12','14','Style Status Report-Cut Details','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('13','15','Style Status Report - Fabric','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('14','17','Cutting WIP','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('15','18','Embellishment Garment WIP','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('16','19','Embellishment Panel WIP','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('17','20','Fabric WIP','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('18','21','FG WIP','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('19','22','Packing WIP','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('20','23','Sewing WIP','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('21','25','Inspection Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('22','26','Inspection Summary','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('23','27','Supplier Claim Log','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('24','28','Supplier Performance Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('25','30','Carton WIP','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('26','31','COD Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('27','32','RM Availability','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('28','33','Sewing Performance','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('29','35','Report Portal','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('30','36','TecLink','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('31','40','Advice of Dispatch','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('32','41','Advice of Dispatch - Surplus','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('33','42','Carton Flow Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('34','43','CTPAT','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('35','44','Cut To Ship Analysis Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('36','45','FG Stock Summary','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('37','46','M3 Offline Dispatch','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('38','47','Out of Ratio Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('39','48','Weekly Delivery Status Report(Live)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('40','50','Balance Sheet (Live)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('41','51','Delivery Failure Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('42','52','Extra Shipment Details Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('43','53','FR Plan VS Actual Analysis','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('44','54','Order Status Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('45','55','Orders Summary Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('46','56','Plan Achievement Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('47','57','Production Status Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('48','58','Weekly Delivery Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('49','60','Critical Rejection Report - Above 0.4%','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('50','61','Daily Rejection Analysis','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('51','62','Daily Rejection Detail Report - Module Level','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('52','63','Daily Rejection Detail Report - Style Level','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('53','64','FCA Failed Log','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('54','65','Quality Journal','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('55','66','Rejection Analysis Charts - Fabric','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('56','67','Rejection Analysis Charts - Supplier Wise(Fabric)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('57','68','Rejection Summary Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('58','69','Sample Room Transaction Log','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('59','71','Back Dated Output Reported List','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('60','72','Daily Efficiency','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('61','73','Daily SAH Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('62','74','Day Downtime Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('63','75','Department Downtime','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('64','76','Downtime Log','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('65','77','First Hour Output','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('66','78','Grand Efficiency Summary','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('67','79','Hourly Efficiency','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('68','80','Hourly Efficiency(Rework)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('69','81','Module Downtime','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('70','82','Output Deleted List','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('71','83','Style Analysis Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('72','84','Style Downtime','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('73','85','Weekly Style Progress','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('74','87','(AMT) MRN Transaction Log','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('75','88','Fabric Issued Track','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('76','90','GRN Quick Search','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('77','91','GRN to Production Pendings','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('78','92','M3 Sticker Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('79','93','RM Manual Transactions Log','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('80','94','RM Stock Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('81','96','Incentive Ladder','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('82','97','SMO Incentive Summary','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('83','98','SOP Video Portal','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('84','102','PSD wise BOM Pending Summary','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('85','1462','Schedule Clubbing','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('86','103','PSD wise BOM Summary','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('87','104','PSD wise Summary','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('88','105','Schedule BOM Summary','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('89','106','Single Window Summary','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('90','1461','MRN','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('91','107','Style wise Material Status','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('92','110','CAD Job Priority','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('93','111','CAD Job Priority-2','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('94','112','Color Clubbing','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('95','113','Cut Qty Reporting','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('96','114','Cut-Bundle Sticker Printing','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('97','115','Data Update Tool (V3)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('98','116','Data Upload','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('99','117','Delete Lay Plan','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('100','118','KPI Parameter Update','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('101','119','Lay Plan Preparation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('102','120','Panel Input Reporting','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('103','121','Plot Job Priority','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('104','122','Recut Plot Job Priority','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('105','123','Sewing Input Modification','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('106','125','Embellishment Data Upload','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('107','126','Upload Tool','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('108','129','Confirm Inspection Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('109','130','Roll Inspection Report Update','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('110','131','Supplier Claim Request Form','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('111','132','Supplier Performance Report \nUpdate','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('112','134','Security Checkout','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('113','136','Inteface Dashboard','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('114','137','M3-Excess RM Requisition','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('115','138','M3-Write Off Information System','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('116','139','Carton Packing','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('117','140','Audit Log','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('118','141','Re Confirmation Form','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('119','142','ENP GF Received','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('120','144','4 Point System','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('121','145','Bug Solutions','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('122','146','Carton Check-In','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('123','147','Delete Packing List','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('124','148','Excess Garment Receiving','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('125','149','IU Update','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('126','150','M&S Packs List Generation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('127','151','Packing List Generation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('128','152','Reserve for Dispatch','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('129','153','Split Labels','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('130','154','Update Carton Quantities','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('131','155','Update Carton Weights','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('132','156','Weekly Dashboard Update (Live)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('133','158','Delivery Schedule Update','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('134','159','Weekly Delivery Plan Upload','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('135','160','IPS Planning Board Allocation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('136','161','IU Delivery Schedule Update','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('137','162','Input Job Level Planning','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('138','163','Weekly Delivery Upload Tool','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('139','164','Module Count Settings','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('140','165','Monthly SAH Updation Form','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('141','166','Order Qty Update','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('142','167','Style Group Settings','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('143','169','Additional Panel Destroy Track','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('144','170','Additional Panel Module Input Update Form','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('145','171','Additional Panel Track','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('146','172','FCA Status Update','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('147','173','Panel Receiving','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('148','174','Rejection Reversal Form','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('149','175','Rejection Update','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('150','176','Sample Schedule Confirmation Form','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('151','177','Samples Update','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('152','178','Samples Update (IMS)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('153','180','Delete RM Receiving','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('154','181','Fabric Issuing Track','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('155','182','Location Labels','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('156','183','Location Transfer','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('157','184','M3 Picking List','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('158','185','Online Barcode Scanning','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('159','186','RM Manual Request Form','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('160','187','RM Migration Application','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('161','188','Sticker Report Upload Tool','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('162','189','Update Locations','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('163','190','Update RM Issuing','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('164','191','Update RM Receiving','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('165','192','Update RM Returns','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('166','194','Additional Panel Input Request Form','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('167','195','Change Password','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('168','196','Critical IE Workstudy Updates','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('169','197','Data Backup','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('170','198','Downtime Update','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('171','199','Modify SMV_NOP','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('172','200','MRN Request Form','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('173','201','Output Verification','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('174','202','Recut Docket Request','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('175','203','Sewing Out Reporting','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('176','204','Update Plan Efficiency','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('177','205','Update Style Details','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('178','207','Confirm Internal Destroy','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('179','208','Confirm Offered Destroy','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('180','209','Location MAP','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('181','210','Rejection/Panels Location Update','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('182','211','Reserve for Audit/Internal Destory','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('183','213','Daily Incentive Journal','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('184','214','Factory level Incentive Amount Approval','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('185','215','Generate The Module And Shift Wise Incentive Sheets','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('186','216','Incentive Ladder Update Tool','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('187','217','Module Wise Incentive Sheets Approval','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('188','218','PreSetup Excel Upload ','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('189','219','Process Incentives','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('190','220','SOP Video Portal - Video Upload','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('191','510','(HPT) Hourly Production Tracking Dashboard','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('192','511','(PLD) Production Live Dashboard','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('193','512','(RTS) Recut DashBoard','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('194','513','(WDP) Weekly Delivery Plan','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('195','514','CPS','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('196','515','EMS','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('197','516','ESD (Extra Shipment Monitoring Dashboard)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('198','517','Factory View','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('199','518','IMS','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('200','519','IPS','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('201','520','IU Clock','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('202','521','LMS','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('203','522','RLS','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('204','523','RMS','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('205','524','TMS','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('206','525','TPS','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('207','526','Cut Dockets','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('208','527','Production Review','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('209','528','Embellishment Monitoring Sheet','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('210','529','Packing List','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('211','530','Cut Plan','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('212','1501','Update Employee Attendance','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('213','1500','Upload FR(VP)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('214','780','Future Delivery Status Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('215','1553','Module & Section','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('216','1554','Supplier','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('217','1552','Downtime log Reasons','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('218','1551','Pack Methods','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('219','1550','Cutting Tables','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('220','1549','Categories','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('221','1547','UA - View All Users And Assigned Roles','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('222','1546','UA - User Creation And Assign Role','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('223','1545','UA - View All Roles Menus And Permissions Mappings','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('224','1544','UA - Role Menu And Permissions Mapping','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('225','1543','UA - View All Permissions','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('226','1541','UA - View All Roles','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('227','1542','UA - Permission Creation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('228','1540','UA - Role Creation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('229','1538','Packing List generation(Sewing OUT PROCESS)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('230','1536','Mini order Priority','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('231','1535','Add Cartons ','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('232','1533','Re-Order synchronization','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('233','1531','Create Mini Orders','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('234','1530','Bundle Ticket Print','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('235','1529','Bundle Operation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('236','1528','Bundle Deletion','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('237','1527','MRN Confirm','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('238','1526','Recut Mini order Creation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('239','1525','Addinal Cut Miniorder','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('240','1524','Mini Order Delete','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('241','1523','Session Restore','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('242','1522','Bundle Ticket Session','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('243','1521','Bundle Tag Re-Print','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('244','1057','ENP GF Sent','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('245','1058','ENP PF Received','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('246','1059','ENP PF Sent','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('247','1060','ENP Sewing In','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('248','1061','Bundling','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('249','1062','Rejections','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('250','1063','Samples','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('251','1064','Sewing In','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('252','1065','Sewing Out','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('253','1066','Embellishment Summary Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('254','1067','M3 Lay Quantity Reporting','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('255','1068','Excess Garments Received Confirmation Form','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('256','1069','AQL Auditors Login Form','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('257','1070','AQL Auditors Module Allocation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('258','1071','AQL Auditors Users Creation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('259','1088','Excess GMT sent to Embellishment','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('260','1089','FG Stock Reversal Form','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('261','1093','Cut Job Level Planning','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('262','1498','Docket','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('263','1353','RMS Requisition Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('264','1355','IPS Allocation Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('265','1357','Monthly FR Plan - Upload','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('266','1360','Monthly FR Plan - Pending Approval Log','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('267','1363','Monthly FR Plan - Log','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('268','1366','Critical Rejection Report - Above 0.4% (size wise)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('269','1369','Shipment Sample Update (CIF)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('270','1372','Sample Requirement Confirmation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('271','1375','Shipment Samples (IMS)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('272','1378','Day & Module Wise Performance Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('273','1379','Style & Color Level WIP Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('274','1380','Mini order reconcillation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('275','1381','Product Wise Summary Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('276','1383','Last 5 Days Performance Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('277','1384','Day Wise Performance Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('278','1385','Day Module wise Performance','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('279','1386','Bundle Tag Re-Print','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('280','1387','Bundle Re-print Analysis Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('281','1402','Bundle Performance Dashboard','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('282','1404','View Cartons','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('283','1405','Mini Order Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('284','1406','Bundle Ticket Status Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('285','1407','Bundle Operations Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('286','1408','Check List Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('287','1409','Cut Docket Allocation Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('288','1410','Scanned Quantity Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('289','1411','Rejection Quantity Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('290','1412','Lay Plan Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('291','1413','Bundle Split','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('292','1414','Create Mini Orders','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('293','1415','Bundle Ticket Print','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('294','1416','Bundle Operation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('295','1417','Bundle Deletion','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('296','1418','MRN Confirm','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('297','1419','Recut Mini order Creation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('298','1420','Addinal Cut Miniorder','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('299','1421','Mini Order Delete','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('300','1422','Operations Mapping','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('301','1423','Operations Master','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('302','1424','Bundle Opeartions Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('303','1425','Garment Sending','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('304','1426','Garment Receiving','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('305','1432','Bundle Allocation Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('306','1433','Bundle Allocation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('307','1434','Session Restore','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('308','1449','Ratio Packing List Mapping','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('309','1450','Ratio Packing List Generation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('310','1451','Delete Ratio Mapping','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('311','1499','Hourly Cutting Production Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('312','1457','Surplus Stock Summary','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('313','1519','Endline Display','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('314','1460','Jumpers Incentive Sheet','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('315','1463','Schedule Clubbing Split','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('316','1464','Bundle Ticket Session','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('317','1465','Trims Inspection Report Update','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('318','1466','Bundle Generation','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('319','1467','Create Locations','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('320','1468','Locations Dashboard','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('321','1469','Print Panel Sequence Numbers','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('322','1470','Operation Mapping','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('323','1471','Operations Master','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('324','1472','Re-Order synchronization','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('325','1473','Bundle Operations Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('326','1474','Bundle Scanning-Panels','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('327','1475','Garments Sending','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('328','1476','Garment Receiving','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('329','1479','Bundle Barcode Print','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('330','1477','Bundle Operations Dashboard','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('331','1478','Create Sewing Orders','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('332','1480','View Sewing Orders','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('333','1481','Bundles Reversal Scanning','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('334','1482','Update Missing Panels','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('335','1483','Bundles with Missing Panels','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('336','1484','Barcode scanning for Input Job','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('337','1485','Add Locations','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('338','1486','Packing List View(Sewing OUT VIEW)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('339','1488','Create Sewing Jobs','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('340','1489','Sewing Job Ratios','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('341','1490','Delete Sewing Jobs','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('342','1492','Orders Re-Sync','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('343','1493','Sewing Jobs Split','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('344','1494','Out of Ratio Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('345','1495','M3 Offline Dispatch Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('346','1496','Delivery Schedule Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('347','1502','Sewing Out Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('348','1503','Schedule Wise Job Reconciliation Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('349','1504','Cut Qty Reporting Without Roll','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('350','1505','Update CIF','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('351','1506','Update FCA','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('352','1507','Hourly Production Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('353','1508','Hourly Production Report - Section Wise','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('354','1509','Lost Hour Capturing Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('355','1510','Lost Hour Summary Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('356','1511','Lost Hour Summary (SAH - Section Wise)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('357','1512','Lost Hour Capturing (Section Wise)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('358','1513','Critical Style Update','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('359','1514','Sewing job Scanning','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('360','1515','Rejection Update','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('361','1516','Re-Work Capturing','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('362','1517','Quality Endline Display','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('363','1518','Sewing Job Reversal Scanning','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('364','1520','Schedule Clubbing Delete','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('432','1559','Schedules Mix','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('433','1560','Schedules Mix Delete','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('434','1561','Schedules Mix Split','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('435','1562','Jobs Mix Delete','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('436','1563','IMS Dashboard(Schedule Wise)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('437','1565','Order Quantity Update Schedule Wise','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('438','1566','Packing Ratio','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('439','1567','Downtime update','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('440','1568','Sewing Job Create (NEW)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('441','1569','sewing job clubbing','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('442','1570','Order Quantity Update( Schedule Wise )','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('443','1571','Packing List Generation (NEW)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('447','1572','Operation Routing','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('448','1573','Operation Routing','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('449','1574','Update Forecast Qty','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('450','1575','Update Style wise FR Qty','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('451','1576','BundleWise Scanning','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('459','1577','Fabric Request Time','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('460','1577','Fabric Request Time','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('461','1578','IMS Module Transfer Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('462','1579','Update RM Issuing','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('463','190','Update RM Issuing','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('470','1580','Default Operation Work Flow','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('471','1581','Short Key Codes','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('485','1582','Modules','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('486','1583','Work Stations Mapping','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('487','1585','Sections','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('500','1579','Input Job Sequence Planning','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('509','1586','Embellishment Cut Job Level Planning','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('510','1587','EMS Send Dashboard','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('511','1588','EMS Received Dashboard','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('539','1589','Update Locations','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('547','1590','M3 Transactions Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('548','1591','Emb Master','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('584','1593','M3 Transactions Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('597','1594','RM Warehouse Material Receive','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('659','1595','WPT Dashboard','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('660','1597','Add Packing List','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('661','1598','Pack Method Loading','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('662','1599','Carton Club','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('663','1600','Carton Split','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('664','1601','Carton Scanning','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('665','1602','Delete Packing List','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('666','1603','Carton Reversal','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('667','1604','Carton Eligible Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('668','1605','Carton Pack Report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('669','1606','Cut Table Dashboard (Warehouse)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('670','1607','Cut Table Dashboard (Cutting)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('677','1608','Delete Order Details','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('827','1610','Mo Transaction report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('1454','1612','Create Sewing Jobs (Packing List Based)','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('1455','1613','EMS SCAN','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('1639','1614','Remove Jobs From IPS','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('1641','1610','Mo Transaction report','1');
insert into central_administration_sfcs.rbac_role_menu (`role_menu_id`, `menu_pid`, `menu_description`, `roll_id`) values('1642','1616','Cutting Reversal','1');
